11:08:38 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:11:17 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:13:40 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:14:10 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:16:04 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:16:04 PM: DEBUG [dao_usuario.py:30] None
11:25:11 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:25:11 PM: DEBUG [dao_usuario.py:30] Usuario registrado correctamente
11:52:57 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:52:57 PM: DEBUG [dao_usuario.py:30] Usuario registrado correctamente
12:04:55 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:04:55 AM: ERROR [dao_usuario.py:24] Error: El usuario jiquinte ya existe, escoja otro.
12:24:28 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:24:28 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
12:24:28 AM: ERROR [dao_usuario.py:49] Error: Credenciales invalidas. Usuario: jiquinte Contrasena: 101218
12:24:56 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:24:56 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
12:25:32 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:25:32 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
12:25:59 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:25:59 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
12:25:59 AM: DEBUG [dao_usuario.py:45] El usuario jiquinte, con None ha iniciado sesion.
12:26:44 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:26:44 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
12:26:44 AM: DEBUG [dao_usuario.py:46] El usuario robin ha iniciado sesion.
12:43:09 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:44:38 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:44:38 AM: DEBUG [dao_usuario.py:30] Un usuario se registro correctamente: janodroll
12:46:48 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:46:48 AM: DEBUG [dao_usuario.py:30] Un usuario se registro correctamente: janodroll
02:24:40 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:24:40 PM: ERROR [dao_usuario.py:24] Error: El usuario hardness ya existe, escoja otro.
02:25:02 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:25:02 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
02:25:02 PM: ERROR [dao_usuario.py:48] Error: Credenciales invalidas. Usuario: hardness Contrasena: 1234
02:25:15 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:25:15 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
02:25:15 PM: DEBUG [dao_usuario.py:44] El usuario hardness ha iniciado sesion.
02:30:25 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:30:25 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
02:31:02 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:31:02 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
02:31:02 PM: DEBUG [dao_usuario.py:44] El usuario hardness ha iniciado sesion.
02:33:43 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:33:43 PM: ERROR [dao_usuario.py:25] Error: El usuario hardness ya existe, escoja otro.
02:38:29 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:38:29 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
02:38:29 PM: DEBUG [dao_usuario.py:46] El usuario hardness ha iniciado sesion.
02:44:23 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:44:23 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
02:45:43 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:45:43 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
02:45:43 PM: DEBUG [dao_usuario.py:47] El usuario hardness con ID: 1 ha iniciado sesion.
02:54:29 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:54:29 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
02:55:43 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:55:43 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
02:55:55 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
02:55:55 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
03:13:57 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
03:13:57 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
03:13:57 PM: ERROR [dao_usuario.py:50] Error: Credenciales invalidas. Usuario: as Contrasena: as
03:16:39 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
03:16:39 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
03:16:39 PM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
03:18:41 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
03:18:41 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
03:18:41 PM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
03:27:02 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
03:27:02 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
03:27:16 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
03:27:16 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
03:27:16 PM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
03:29:56 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
03:29:56 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
03:29:56 PM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
03:30:20 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
03:30:20 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
03:30:20 PM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
03:38:25 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
03:38:25 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
03:38:25 PM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
03:39:26 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
03:39:26 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
03:39:26 PM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
04:05:36 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
04:05:36 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
04:05:36 PM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
04:06:03 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
04:06:03 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
04:06:03 PM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
04:06:13 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
04:06:13 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
04:06:22 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
04:06:22 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
04:37:57 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
04:37:57 PM: DEBUG [dao_usuario.py:31] Un usuario se registro correctamente: NebulaMaster
04:57:30 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
04:57:30 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
04:57:30 PM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
05:00:30 PM: DEBUG [dao_usuario.py:31] Un usuario se registro correctamente: pepeTola
10:43:31 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:43:31 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:43:31 AM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
10:44:11 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:44:11 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:46:08 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:46:08 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:46:19 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:46:19 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:46:19 AM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
10:47:05 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:47:05 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:47:05 AM: DEBUG [dao_usuario.py:46] El usuario janodroll con ID: 2 ha iniciado sesion.
10:49:59 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:49:59 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:49:59 AM: DEBUG [dao_usuario.py:46] El usuario janodroll con ID: 2 ha iniciado sesion.
10:50:27 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:50:27 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:51:40 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:51:40 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:52:53 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:52:53 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:55:41 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:55:50 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:57:53 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:57:53 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
10:58:48 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
10:58:48 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:00:15 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:00:15 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:00:41 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:00:41 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:01:05 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:01:05 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:01:52 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:01:52 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:03:35 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:03:35 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:06:56 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:06:56 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:07:08 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:07:08 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:07:08 AM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
11:09:04 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:09:04 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:11:36 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:11:36 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:13:34 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:13:34 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:14:29 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:14:29 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:15:37 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:15:37 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:15:37 AM: DEBUG [dao_usuario.py:46] El usuario hardness con ID: 1 ha iniciado sesion.
11:28:21 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:28:21 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:29:50 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:29:50 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:35:34 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:35:34 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:35:51 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:35:51 AM: DEBUG [database.py:40] Se creo el cursor correctamente.
11:39:45 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:40:06 AM: DEBUG [dao_usuario.py:47] El usuario hardness con ID: 1 ha iniciado sesion.
11:41:53 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:41:53 AM: DEBUG [dao_usuario.py:47] El usuario hardness con ID: 1 ha iniciado sesion.
11:42:14 AM: DEBUG [dao_usuario.py:47] El usuario janodroll con ID: 2 ha iniciado sesion.
11:44:26 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:44:26 AM: DEBUG [dao_usuario.py:47] El usuario hardness con ID: 1 ha iniciado sesion.
11:45:01 AM: DEBUG [dao_usuario.py:47] El usuario janodroll con ID: 2 ha iniciado sesion.
11:45:35 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:45:35 AM: DEBUG [dao_usuario.py:47] El usuario janodroll con ID: 2 ha iniciado sesion.
11:50:40 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:51:08 AM: DEBUG [dao_usuario.py:47] El usuario hardness con ID: 1 ha iniciado sesion.
11:57:06 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:57:06 AM: DEBUG [dao_usuario.py:47] El usuario hardness con ID: 1 ha iniciado sesion.
11:57:37 AM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
11:57:37 AM: DEBUG [dao_usuario.py:47] El usuario hardness con ID: 1 ha iniciado sesion.
12:04:29 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:04:29 PM: DEBUG [dao_usuario.py:31] 
Un usuario se registro correctamente: elmochilas123
12:04:44 PM: DEBUG [dao_usuario.py:47] El usuario elmochilas123 con ID: 5 ha iniciado sesion.
12:05:24 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:05:24 PM: DEBUG [dao_usuario.py:47] El usuario elmochilas123 con ID: 5 ha iniciado sesion.
12:16:06 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:16:06 PM: DEBUG [dao_usuario.py:47] El usuario janodroll con ID: 2 ha iniciado sesion.
12:33:25 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:33:25 PM: DEBUG [dao_usuario.py:47] El usuario hardness con ID: 1 ha iniciado sesion.
12:34:07 PM: DEBUG [dao_usuario.py:47] El usuario janodroll con ID: 2 ha iniciado sesion.
12:36:26 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:36:55 PM: DEBUG [dao_usuario.py:47] El usuario janodroll con ID: 2 ha iniciado sesion.
12:37:33 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:37:33 PM: DEBUG [dao_usuario.py:47] El usuario hardness con ID: 1 ha iniciado sesion.
12:37:56 PM: DEBUG [dao_usuario.py:47] El usuario hardness con ID: 1 ha iniciado sesion.
12:42:06 PM: DEBUG [dao_usuario.py:47] El usuario elmochilas123 con ID: 5 ha iniciado sesion.
12:52:40 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:52:40 PM: DEBUG [dao_usuario.py:48] El usuario hardness con ID: 1 ha iniciado sesion.
12:55:06 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:55:06 PM: DEBUG [dao_usuario.py:48] El usuario hardness con ID: 1 ha iniciado sesion.
12:56:55 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:56:55 PM: DEBUG [dao_usuario.py:48] El usuario hardness con ID: 1 ha iniciado sesion.
12:59:10 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
12:59:10 PM: DEBUG [dao_usuario.py:48] El usuario elmochilas123 con ID: 5 ha iniciado sesion.
01:00:26 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
01:00:42 PM: DEBUG [dao_usuario.py:48] El usuario elmochilas123 con ID: 5 ha iniciado sesion.
01:00:49 PM: DEBUG [menu.py:41] elmochilas123 ha dado rango admin a pepeTola
01:02:40 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
01:02:40 PM: DEBUG [dao_usuario.py:48] El usuario hardness con ID: 1 ha iniciado sesion.
01:03:18 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
01:03:18 PM: DEBUG [dao_usuario.py:48] El usuario hardness con ID: 1 ha iniciado sesion.
01:03:46 PM: DEBUG [menu.py:41] (1)hardness ha dado rango admin a NebulaMaster
06:52:47 PM: ERROR [database.py:29] No se logro conectar a la base de datos.
07:54:48 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
07:54:48 PM: DEBUG [dao_usuario.py:48] El usuario hardness con ID: 1 ha iniciado sesion.
07:57:46 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
07:57:46 PM: DEBUG [dao_usuario.py:48] El usuario hardness con ID: 1 ha iniciado sesion.
08:03:59 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:03:59 PM: DEBUG [dao_usuario.py:49] El usuario hardness con ID: 1 ha iniciado sesion.
08:04:04 PM: DEBUG [menu.py:41] (ID: 1) hardness ha dado rango admin a (ID: 4) pepeTola
08:18:38 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:18:38 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:18:43 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
08:19:01 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:19:01 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:19:03 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
08:21:01 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:21:01 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:21:02 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
08:24:01 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:24:01 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:24:02 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
08:24:37 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:24:37 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:24:38 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
08:26:03 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:26:03 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:26:13 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
08:27:45 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:27:45 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:27:54 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
08:30:28 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:30:57 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:30:57 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:30:59 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
08:31:06 PM: DEBUG [menu.py:45] (ID: 1) hardness ha dado rango admin a (ID: 2) janodroll
08:31:49 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:31:49 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:31:50 PM: DEBUG [database.py:40] Se creo el cursor correctamente.
08:31:55 PM: DEBUG [menu.py:45] (ID: 1) hardness ha dado rango admin a (ID: 2) janodroll
08:33:03 PM: DEBUG [database.py:26] Se conecto la base de datos satisfactoriamente.
08:33:03 PM: DEBUG [dao_usuario.py:50] El usuario hardness con ID: 1 ha iniciado sesion.
08:33:09 PM: DEBUG [menu.py:45] (ID: 1) hardness ha dado rango admin a (ID: 3) NebulaMaster
08:33:18 PM: DEBUG [menu.py:45] (ID: 1) hardness ha dado rango admin a (ID: 5) elmochilas123
12:37:17 PM: DEBUG [database.py:43] Se conecto la base de datos satisfactoriamente. <connection object at 0x000002AD4F361140; dsn: 'user=postgres password=xxx dbname=sistema_prueba host=127.0.0.1 port=5432', closed: 0>
12:39:08 PM: DEBUG [database.py:43] Se conecto la base de datos satisfactoriamente. <connection object at 0x000001F54221D140; dsn: 'user=postgres password=xxx dbname=sistema_prueba host=127.0.0.1 port=5432', closed: 0>
12:39:08 PM: DEBUG [dao_usuario.py:71] El usuario hardness con ID: 1 ha iniciado sesion.
12:57:42 PM: DEBUG [database.py:43] Se conecto la base de datos satisfactoriamente. <connection object at 0x000001536C7E1140; dsn: 'user=postgres password=xxx dbname=sistema_prueba host=127.0.0.1 port=5432', closed: 0>
12:57:42 PM: DEBUG [dao_usuario.py:71] El usuario hardness con ID: 1 ha iniciado sesion.
12:57:59 PM: DEBUG [menu.py:57] (ID: 1) hardness ha actualizado su contrasenia de 12345 a 101218Jo
01:00:53 PM: DEBUG [database.py:43] Se conecto la base de datos satisfactoriamente. <connection object at 0x000002364FB2D140; dsn: 'user=postgres password=xxx dbname=sistema_prueba host=127.0.0.1 port=5432', closed: 0>
01:00:53 PM: DEBUG [dao_usuario.py:71] El usuario hardness con ID: 1 ha iniciado sesion.
01:01:06 PM: DEBUG [menu.py:57] (ID: 1) hardness ha actualizado su contrasenia de 12345 a 101218Jo
01:04:03 PM: DEBUG [menu.py:57] (ID: 1) hardness ha actualizado su contrasenia de 101218 a 12345
01:08:28 PM: DEBUG [database.py:43] Se conecto la base de datos satisfactoriamente. <connection object at 0x00000241A65D1140; dsn: 'user=postgres password=xxx dbname=sistema_prueba host=127.0.0.1 port=5432', closed: 0>
01:08:28 PM: DEBUG [dao_usuario.py:71] El usuario elmochilas123 con ID: 5 ha iniciado sesion.
01:08:40 PM: DEBUG [menu.py:60] (ID: 5) elmochilas123 ha actualizado su contrasenia de Penecertero12 a 123
01:09:39 PM: DEBUG [database.py:43] Se conecto la base de datos satisfactoriamente. <connection object at 0x000001906A84D140; dsn: 'user=postgres password=xxx dbname=sistema_prueba host=127.0.0.1 port=5432', closed: 0>
01:09:39 PM: DEBUG [dao_usuario.py:71] El usuario elmochilas123 con ID: 5 ha iniciado sesion.
01:10:39 PM: DEBUG [menu.py:60] (ID: 5) elmochilas123 ha actualizado su contrasenia de 123 a 101218Jo
01:12:07 PM: DEBUG [menu.py:60] (ID: 5) elmochilas123 ha actualizado su contrasenia de 101218Jo a 1
01:18:11 PM: DEBUG [database.py:43] Se conecto la base de datos satisfactoriamente. <connection object at 0x0000021C1B63D250; dsn: 'user=postgres password=xxx dbname=sistema_prueba host=127.0.0.1 port=5432', closed: 0>
01:18:11 PM: DEBUG [dao_usuario.py:71] El usuario elmochilas123 con ID: 5 ha iniciado sesion.
01:20:15 PM: DEBUG [database.py:43] Se conecto la base de datos satisfactoriamente. <connection object at 0x00000212A9AED250; dsn: 'user=postgres password=xxx dbname=sistema_prueba host=127.0.0.1 port=5432', closed: 0>
01:20:15 PM: DEBUG [dao_usuario.py:71] El usuario elmochilas123 con ID: 5 ha iniciado sesion.
01:20:27 PM: DEBUG [menu.py:77] (ID: 5) elmochilas123 ha actualizado su contrasenia de 1 a MochilaViajera123
